#!/usr/bin/python3
 
import pymysql
f = open("./output.txt","r") 

# 打开数据库连接
db = pymysql.connect("localhost","test","1","TEST" )
 
# 使用 cursor() 方法创建一个游标对象 cursor
cursor = db.cursor()

line = f.readline()
while line:
	# 使用 execute() 方法执行 SQL，如果表存在则删除
	
	cursor.execute("DROP TABLE IF EXISTS %s" %line)
	linename="T_"+line 
	# 使用预处理语句创建表
	sql = """CREATE TABLE %s (
         	EXCHANGEID  VARCHAR(100) NOT NULL,
		INSTRUMENTID VARCHAR(100) NOT NULL,
		LASTPRICE DOUBLE,
		BIDPRICE1 DOUBLE,		
		BIDPRICE2 DOUBLE,		
		BIDPRICE3 DOUBLE,		
		BIDPRICE4 DOUBLE,		
		BIDPRICE5 DOUBLE,		
		BIDVOLUME1 DOUBLE,
		BIDVOLUME2 DOUBLE,
		BIDVOLUME3 DOUBLE,
		BIDVOLUME4 DOUBLE,
		BIDVOLUME5 DOUBLE,
		ASKPRICE1 DOUBLE,
		ASKPRICE2 DOUBLE,
		ASKPRICE3 DOUBLE,
		ASKPRICE4 DOUBLE,
		ASKPRICE5 DOUBLE,
		ASKVOLUME1 DOUBLE,
		ASKVOLUME2 DOUBLE,
		ASKVOLUME3 DOUBLE,
		ASKVOLUME4 DOUBLE,
		ASKVOLUME5 DOUBLE,
		VOLUME INT,
		VOLUME_TODAY INT,
		VOLUME_TICK INT,
		OPENINTEREST INT,
		UPDATETIME_UPDATEMILLISEC DATETIME,
		TRADINGDAY DATE,
		OPENPRICE DOUBLE,
		HIGHESTPRICE DOUBLE,
		LOWESTPRICE DOUBLE,
		PRECLOSEPRICE DOUBLE,
		UPPERLIMITPRICE DOUBLE,
		LOWERLIMITPRICE DOUBLE,
		PRIMARY KEY (UPDATETIME_UPDATEMILLISEC)
		)""" %linename
	cursor.execute(sql)
	
	linename = "K_1m_"+line
	sql= """CREATE TABLE %s (
		SYMBOL VARCHAR(100) NOT NULL,
		EXCHANGE VARCHAR(100) NOT NULL,
		DATE DATETIME,
		TIME TIME,
		VOLUME DOUBLE,
		OPENINTEREST DOUBLE,
		OPENPRICE DOUBLE,
		HIGHPRICE DOUBLE,
		LOWPRICE DOUBLE,
		CLOSEPRICE DOUBLE,
		VOLUMEPERMIN DOUBLE
	)""" %linename
	cursor.execute(sql)

	linename = "K_5m_"+line
	sql= """CREATE TABLE %s (
		SYMBOL VARCHAR(100) NOT NULL,
		EXCHANGE VARCHAR(100) NOT NULL,
		DATE DATETIME,
		TIME TIME,
		VOLUME DOUBLE,
		OPENINTEREST DOUBLE,
		OPENPRICE DOUBLE,
		HIGHPRICE DOUBLE,
		LOWPRICE DOUBLE,
		CLOSEPRICE DOUBLE,
		VOLUMEPERMIN DOUBLE
	)""" %linename
	cursor.execute(sql)

	linename = "K_15m_"+line
	sql= """CREATE TABLE %s (
		SYMBOL VARCHAR(100) NOT NULL,
		EXCHANGE VARCHAR(100) NOT NULL,
		DATE DATETIME,
		TIME TIME,
		VOLUME DOUBLE,
		OPENINTEREST DOUBLE,
		OPENPRICE DOUBLE,
		HIGHPRICE DOUBLE,
		LOWPRICE DOUBLE,
		CLOSEPRICE DOUBLE,
		VOLUMEPERMIN DOUBLE
	)""" %linename
	cursor.execute(sql)

	linename = "K_30m_"+line
	sql= """CREATE TABLE %s (
		SYMBOL VARCHAR(100) NOT NULL,
		EXCHANGE VARCHAR(100) NOT NULL,
		DATE DATETIME,
		TIME TIME,
		VOLUME DOUBLE,
		OPENINTEREST DOUBLE,
		OPENPRICE DOUBLE,
		HIGHPRICE DOUBLE,
		LOWPRICE DOUBLE,
		CLOSEPRICE DOUBLE,
		VOLUMEPERMIN DOUBLE
	)""" %linename
	cursor.execute(sql)

	linename = "K_1h_"+line
	sql= """CREATE TABLE %s (
		SYMBOL VARCHAR(100) NOT NULL,
		EXCHANGE VARCHAR(100) NOT NULL,
		DATE DATETIME,
		TIME TIME,
		VOLUME DOUBLE,
		OPENINTEREST DOUBLE,
		OPENPRICE DOUBLE,
		HIGHPRICE DOUBLE,
		LOWPRICE DOUBLE,
		CLOSEPRICE DOUBLE,
		VOLUMEPERMIN DOUBLE
	)""" %linename
	cursor.execute(sql)

	linename = "K_4h_"+line
	sql= """CREATE TABLE %s (
		SYMBOL VARCHAR(100) NOT NULL,
		EXCHANGE VARCHAR(100) NOT NULL,
		DATE DATETIME,
		TIME TIME,
		VOLUME DOUBLE,
		OPENINTEREST DOUBLE,
		OPENPRICE DOUBLE,
		HIGHPRICE DOUBLE,
		LOWPRICE DOUBLE,
		CLOSEPRICE DOUBLE,
		VOLUMEPERMIN DOUBLE
	)""" %linename
	cursor.execute(sql)

	linename = "K_1d_"+line
	sql= """CREATE TABLE %s (
		SYMBOL VARCHAR(100) NOT NULL,
		EXCHANGE VARCHAR(100) NOT NULL,
		DATE DATETIME,
		TIME TIME,
		VOLUME DOUBLE,
		OPENINTEREST DOUBLE,
		OPENPRICE DOUBLE,
		HIGHPRICE DOUBLE,
		LOWPRICE DOUBLE,
		CLOSEPRICE DOUBLE,
		VOLUMEPERMIN DOUBLE
	)""" %linename
	cursor.execute(sql)

	linename = "K_1w_"+line
	sql= """CREATE TABLE %s (
		SYMBOL VARCHAR(100) NOT NULL,
		EXCHANGE VARCHAR(100) NOT NULL,
		DATE DATETIME,
		TIME TIME,
		VOLUME DOUBLE,
		OPENINTEREST DOUBLE,
		OPENPRICE DOUBLE,
		HIGHPRICE DOUBLE,
		LOWPRICE DOUBLE,
		CLOSEPRICE DOUBLE,
		VOLUMEPERMIN DOUBLE
	)""" %linename
	cursor.execute(sql)

		
	line = f.readline()
f.close()
 
# 关闭数据库连接
db.close()
